use serde::{Deserialize, Serialize};

use crate::error::{CoreError, Result};
use crate::frontmatter::Frontmatter;
use crate::identity::PageIdentity;
use crate::page_type::PageType;
use crate::path::WikiPath;

pub type TemplateId = Template;

#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Template {
    Generic,
    Research,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum FieldType {
    String,
    List,
    Number,
    Date,
    Enum,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum NamingPattern {
    TitleSlug,
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub struct FieldDef {
    field: String,
    field_type: FieldType,
    allowed_values: Vec<String>,
    required: bool,
}

impl FieldDef {
    pub fn new(field: impl Into<String>, field_type: FieldType, required: bool) -> Self {
        Self {
            field: field.into(),
            field_type,
            allowed_values: Vec::new(),
            required,
        }
    }

    pub fn field(&self) -> &str {
        &self.field
    }

    pub fn field_type(&self) -> FieldType {
        self.field_type
    }

    pub fn allowed_values(&self) -> &[String] {
        &self.allowed_values
    }

    pub fn required(&self) -> bool {
        self.required
    }
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub struct PageTypeDef {
    name: PageType,
    directory: String,
    description: String,
    extra_fields: Vec<FieldDef>,
    naming_pattern: NamingPattern,
}

impl PageTypeDef {
    pub fn new(name: PageType, description: impl Into<String>) -> Self {
        Self {
            name,
            directory: name.default_directory().to_owned(),
            description: description.into(),
            extra_fields: Vec::new(),
            naming_pattern: NamingPattern::TitleSlug,
        }
    }

    pub fn name(&self) -> PageType {
        self.name
    }

    pub fn directory(&self) -> &str {
        &self.directory
    }

    pub fn description(&self) -> &str {
        &self.description
    }

    pub fn extra_fields(&self) -> &[FieldDef] {
        &self.extra_fields
    }

    pub fn naming_pattern(&self) -> NamingPattern {
        self.naming_pattern
    }
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub struct WikiTemplate {
    id: Template,
    name: String,
    icon: String,
    description: String,
    base_types: Vec<PageTypeDef>,
    extended_types: Vec<PageTypeDef>,
    schema_prompt: String,
}

impl WikiTemplate {
    pub fn id(&self) -> Template {
        self.id
    }

    pub fn name(&self) -> &str {
        &self.name
    }

    pub fn icon(&self) -> &str {
        &self.icon
    }

    pub fn description(&self) -> &str {
        &self.description
    }

    pub fn base_types(&self) -> &[PageTypeDef] {
        &self.base_types
    }

    pub fn extended_types(&self) -> &[PageTypeDef] {
        &self.extended_types
    }

    pub fn schema_prompt(&self) -> &str {
        &self.schema_prompt
    }

    pub fn page_type(&self, page_type: PageType) -> Option<&PageTypeDef> {
        self.base_types
            .iter()
            .chain(&self.extended_types)
            .find(|definition| definition.name() == page_type)
    }

    pub fn validate_doc(&self, path: &WikiPath, frontmatter: &Frontmatter) -> Result<PageIdentity> {
        if path.is_reserved() {
            return Err(CoreError::Template(format!(
                "{path} is generated by the engine"
            )));
        }

        let identity = PageIdentity::new(self.id, frontmatter.page_type(), frontmatter.title())?;
        let definition = self.page_type(frontmatter.page_type()).ok_or_else(|| {
            CoreError::Template(format!(
                "{} template does not allow {} pages",
                self.id.as_str(),
                frontmatter.page_type().as_str()
            ))
        })?;
        if path.directory() != definition.directory() {
            return Err(CoreError::Template(format!(
                "{} pages must live in {}",
                frontmatter.page_type().as_str(),
                definition.directory()
            )));
        }
        Ok(identity)
    }
}

impl Template {
    pub const ALL: [Self; 2] = [Self::Generic, Self::Research];

    pub fn as_str(self) -> &'static str {
        match self {
            Self::Generic => "generic",
            Self::Research => "research",
        }
    }

    pub fn default_template() -> Self {
        Self::Generic
    }

    pub fn allows(self, page_type: PageType) -> bool {
        self.definition().page_type(page_type).is_some()
    }

    pub fn definition(self) -> WikiTemplate {
        match self {
            Self::Generic => generic_definition(),
            Self::Research => research_definition(),
        }
    }
}

fn base_definitions() -> Vec<PageTypeDef> {
    vec![
        PageTypeDef::new(
            PageType::Entity,
            "A named actor, product, system, or person.",
        ),
        PageTypeDef::new(PageType::Concept, "A reusable technical idea or mechanism."),
        PageTypeDef::new(
            PageType::Source,
            "A point-in-time representation of one Source Version.",
        ),
        PageTypeDef::new(
            PageType::Query,
            "A reusable question and its current answer.",
        ),
        PageTypeDef::new(
            PageType::Comparison,
            "A structured comparison of entities or concepts.",
        ),
        PageTypeDef::new(
            PageType::Synthesis,
            "A synthesis across sources and concepts.",
        ),
        PageTypeDef::new(PageType::Overview, "A curated entry-point overview."),
    ]
}

fn research_definitions() -> Vec<PageTypeDef> {
    vec![
        PageTypeDef::new(
            PageType::Thesis,
            "A claim or hypothesis under investigation.",
        ),
        PageTypeDef::new(
            PageType::Methodology,
            "A method used to support or test a thesis.",
        ),
        PageTypeDef::new(PageType::Finding, "An evidence-backed research result."),
    ]
}

fn generic_definition() -> WikiTemplate {
    WikiTemplate {
        id: Template::Generic,
        name: "Generic".to_owned(),
        icon: "notebook".to_owned(),
        description: "A general-purpose starting point using only base page types.".to_owned(),
        base_types: base_definitions(),
        extended_types: Vec::new(),
        schema_prompt: "Use only base page types and keep every claim attributable to a source."
            .to_owned(),
    }
}

fn research_definition() -> WikiTemplate {
    WikiTemplate {
        id: Template::Research,
        name: "Research".to_owned(),
        icon: "microscope".to_owned(),
        description: "Research notes with explicit thesis, methodology, and finding pages."
            .to_owned(),
        base_types: base_definitions(),
        extended_types: research_definitions(),
        schema_prompt:
            "Track thesis, methodology, finding, entities, concepts, and source evidence."
                .to_owned(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn exposes_the_mvp_templates() {
        assert_eq!(Template::Generic.definition().extended_types().len(), 0);
        assert_eq!(Template::Research.definition().extended_types().len(), 3);
        assert!(Template::Generic.allows(PageType::Entity));
        assert!(!Template::Generic.allows(PageType::Thesis));
    }

    #[test]
    fn validates_allowed_routes() -> crate::Result<()> {
        let path = WikiPath::parse("wiki/thesis/Consensus.md")?;
        let frontmatter = crate::frontmatter::Frontmatter::new(
            PageType::Thesis,
            "Consensus",
            crate::date::IsoDate::parse("2026-09-07")?,
            crate::date::IsoDate::parse("2026-09-07")?,
            Vec::new(),
            Vec::new(),
            Vec::new(),
            Vec::new(),
        )?;
        assert!(
            Template::Research
                .definition()
                .validate_doc(&path, &frontmatter)
                .is_ok()
        );
        assert!(
            Template::Generic
                .definition()
                .validate_doc(&path, &frontmatter)
                .is_err()
        );
        Ok(())
    }
}
